# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

dammy = User.create(name: "User 1", photo: "no_image.png", bio: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit")

dammy_post_one = Post.create(title: "Post 1", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum henrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: dammy)

dammy_post_two = Post.create(title: "Post 2", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: dammy)

dammy_post_three = Post.create(title: "Post 3", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: dammy)

dammy_post_four = Post.create(title: "Post 4", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: dammy)

dammy_post_five = Post.create(title: "Post 5", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: dammy)

dammy_comment_one = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_one)
dammy_comment_two = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_one)
dammy_comment_three = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_two)
dammy_comment_four = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_one)
dammy_comment_five = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_three)
dammy_comment_six = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_three)
dammy_comment_seven = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_three)
dammy_comment_eight = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_four)
dammy_comment_nine = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_four)
dammy_comment_ten = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_five)
dammy_comment_eleven = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_five)
dammy_comment_twelve = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_five)
dammy_comment_thirteen = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: dammy, post: dammy_post_five)

dammy_like_one = Like.create(author: dammy, post: dammy_post_one)
dammy_like_two = Like.create(author: dammy, post: dammy_post_two)
dammy_like_three = Like.create(author: dammy, post: dammy_post_three)
dammy_like_four = Like.create(author: dammy, post: dammy_post_four)
dammy_like_five = Like.create(author: dammy, post: dammy_post_five)

fola = User.create(name: "User 2", photo: "no_image.png", bio: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit")

fola_post_one = Post.create(title: "Post 1", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: fola)

fola_post_two = Post.create(title: "Post 2", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: fola)

fola_post_three = Post.create(title: "Post 3", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: fola)

fola_comment_one = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_one)
fola_comment_two = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_one)
fola_comment_three = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_one)
fola_comment_four = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_two)
fola_comment_five = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_two)
fola_comment_six = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_three)
fola_comment_seven = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_three)
fola_comment_eight = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_three)
fola_comment_nine = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: fola, post: fola_post_three)

fola_like_one = Like.create(author: fola, post: fola_post_one)
fola_like_two = Like.create(author: fola, post: fola_post_one)
fola_like_three = Like.create(author: fola, post: fola_post_two)
fola_like_four = Like.create(author: fola, post: fola_post_three)

nike = User.create(name: "User 3", photo: "no_image.png", bio: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit")

nike_post_one = Post.create(title: "Post 1", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: nike)

nike_post_two = Post.create(title: "Post 2", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: nike)

nike_comment_one = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_one)
nike_comment_two = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_one)
nike_comment_three = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_one)
nike_comment_four = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_one)
nike_comment_five = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_one)
nike_comment_six = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_two)
nike_comment_seven = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_two)
nike_comment_eight = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: nike, post: nike_post_two)

nike_like_one = Like.create(author: nike, post: nike_post_one)
nike_like_two = Like.create(author: nike, post: nike_post_two)

demola = User.create(name: "User 4", photo: "no_image.png", bio: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit")

demola_post_one = Post.create(title: "Post 1", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: demola)

demola_post_two = Post.create(title: "Post 2", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: demola)

demola_post_three = Post.create(title: "Post 3", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: demola)

demola_post_four = Post.create(title: "Post 4", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: demola)

demola_comment_one = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: demola, post: demola_post_one)
demola_comment_two = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: demola, post: demola_post_two)
demola_comment_three = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: demola, post: demola_post_two)
demola_comment_four = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: demola, post: demola_post_two)
demola_comment_five = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: demola, post: demola_post_four)
demola_comment_six = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: demola, post: demola_post_four)

demola_like_one = Like.create(author: demola, post: demola_post_one)
demola_like_two = Like.create(author: demola, post: demola_post_two)
demola_like_three = Like.create(author: demola, post: demola_post_three)
demola_like_four = Like.create(author: demola, post: demola_post_four)

yinka = User.create(name: "User 5", photo: "no_image.png", bio: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit")

yinka_post_one = Post.create(title: "Post 1", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: yinka)

yinka_comment_one = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: yinka, post: yinka_post_one)
yinka_comment_two = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: yinka, post: yinka_post_one)
yinka_comment_three = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: yinka, post: yinka_post_one)

yinka_like_one = Like.create(author: yinka, post: yinka_post_one)
yinka_like_one = Like.create(author: yinka, post: yinka_post_one)
yinka_like_one = Like.create(author: yinka, post: yinka_post_one)

tunde = User.create(name: "User 6", photo: "no_image.png", bio: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit")

tunde_post_one = Post.create(title: "Post 1", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: tunde)


tunde_post_two = Post.create(title: "Post 2", text: "Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis.Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus. Bibendum class pellentesque at malesuada dapibus cubilia egestas aptent scelerisque. Sodales tempor tellus diam, ridiculus lorem lobortis consectetur massa. Leo ipsum euismod nam dignissim porttitor posuere. Dui elit, velit praesent a. Elementum pretium nulla lobortis arcu dui interdum hendrerit adipiscing ad vehicula conubia purus. Proin enim ullamcorper, duis justo etiam vestibulum litora eu mauris primis. Pulvinar dis mauris lacus. Suscipit accumsan nisi taciti interdum dapibus porta ad fusce lectus.", author: tunde)

tunde_comment_one = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: tunde, post: tunde_post_one)
tunde_comment_two = Comment.create(text: "Leo ipsum euismod nam dignissim porttitor posuere", author: tunde, post: tunde_post_two)

tunde_like_one = Like.create(author: tunde, post: tunde_post_one)
tunde_like_two = Like.create(author: tunde, post: tunde_post_two)
tunde_like_one = Like.create(author: tunde, post: tunde_post_one)
